services:
  - type: web
    name: medigraph
    runtime: python
    buildCommand: "pip install jaclang==0.10.2 byllm==0.4.20 python-dotenv requests"
    startCommand: "pip install jaclang==0.10.2 byllm==0.4.20 python-dotenv requests && jac start main.jac --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
