import { jsPDF } from 'jspdf';

const RISK_LABEL = {
  safe: 'No major issues found',
  caution: 'Worth discussing with your doctor',
  warning: 'Needs attention before your next visit',
  danger: 'Urgent — contact your doctor soon',
};

const SEV_LABEL = {
  low: 'Low concern',
  moderate: 'Moderate concern',
  high: 'High concern',
  critical: 'Critical — seek medical advice',
};

/** Generate a patient-friendly PDF to share with their doctor. */
export function downloadDoctorReport({ patient, meds, report }) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const margin = 48;
  const pageW = doc.internal.pageSize.getWidth();
  const maxW = pageW - margin * 2;
  let y = margin;

  const line = (text, opts = {}) => {
    const size = opts.size ?? 11;
    const style = opts.bold ? 'bold' : 'normal';
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text, maxW);
    for (const ln of lines) {
      if (y > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(ln, margin, y);
      y += size * 1.35;
    }
  };

  doc.setTextColor(30, 41, 59);
  line('MediGraph — Medication Safety Summary', { size: 16, bold: true });
  y += 4;
  line('Prepared for your healthcare provider', { size: 10 });
  line(`Generated: ${report?.generated_at ?? new Date().toISOString().slice(0, 19)}`, { size: 9 });
  y += 10;

  line(`Patient: ${patient.name}`, { bold: true });
  line(`Age: ${patient.age} · Kidney function (GFR): ${patient.kidney_gfr ?? patient.kidney_function_gfr} mL/min`);
  y += 8;

  line('Current medications', { size: 13, bold: true });
  if (!meds?.length) {
    line('None listed.');
  } else {
    for (const m of meds) {
      line(`• ${m.name} — ${m.dose_mg} mg, ${m.frequency}`);
    }
  }
  y += 10;

  const overall = report?.overall_risk ?? 'safe';
  line(`Overall assessment: ${RISK_LABEL[overall] ?? overall}`, { bold: true });
  line(`${report?.conflicts_found ?? 0} potential interaction(s) flagged.`, { size: 10 });
  y += 10;

  if (report?.findings?.length) {
    line('Interaction alerts (patient-friendly summary)', { size: 13, bold: true });
    report.findings.forEach((f, i) => {
      y += 4;
      line(`${i + 1}. ${f.drugs?.join(' + ') ?? 'Medications'} — ${SEV_LABEL[f.severity] ?? f.severity}`, { bold: true });
      if (f.summary) line(f.summary);
      if (f.clinical_risk) line(`Risk for you: ${f.clinical_risk}`, { size: 10 });
      if (f.recommendation) line(`Suggested next step: ${f.recommendation}`, { size: 10 });
      if (f.mechanism) line(`Clinical details: ${f.mechanism}`, { size: 9 });
      y += 6;
    });
  }

  y += 8;
  doc.setTextColor(100, 116, 139);
  line(
    'Disclaimer: This report was generated by MediGraph for educational purposes. '
    + 'It does not replace professional medical advice. All medication changes should be made with a licensed prescriber.',
    { size: 8 },
  );

  const safeName = (patient.name || 'patient').replace(/\s+/g, '-').toLowerCase();
  doc.save(`medigraph-report-${safeName}.pdf`);
}
